title: SedationH Blog
author: SedationH
email: sedationh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  try github tutorial

# social links
github_username:  SedationH # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima

